### ISSUE TITLE
Google and China

### ISSUE THREAD

**Issue by runn1ng** [feross/connectivity#1]
China blocks Google.

I am not sure what does pinging Google like this script does actually do in China, but it shouldn't be relied on.

We hit a similar issue with using Google Web fonts in our app; since Google Web fonts are blocked in China, whole app looked ugly.

**Comment by runn1ng** [comment]
And it seems that in browser, you use navigator.online; that doesn't seem to work on Chrome on Linux.

**Comment by feross** [comment]
> China blocks Google.

Fixed by changing `google.com` to `example.com`. 

> in browser, you use navigator.online; that doesn't seem to work on Chrome on Linux.

Sounds like a browser bug. Can you file an issue with Chromium? We're using the property as intended.

**Comment by feross** [comment]
Released the fix as 1.0.0
